# Generated by Django 4.1.3 on 2022-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Database Image/Aboutcompany')),
                ('Desc', models.CharField(max_length=500)),
                ('Icon', models.ImageField(upload_to='Database Image/Abouticon')),
                ('Company', models.CharField(max_length=100)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
