# Generated by Django 4.1.3 on 2022-11-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(blank=True, max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=10)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ourArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Areaimage')),
                ('Title', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=50)),
                ('Group', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=10)),
                ('Desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ourservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Dataimage')),
                ('title', models.CharField(max_length=100)),
                ('people', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('lista', models.CharField(max_length=100)),
                ('listb', models.CharField(max_length=100)),
                ('listc', models.CharField(max_length=100)),
                ('listd', models.CharField(blank=True, max_length=100)),
                ('liste', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
