# Generated by Django 4.1.3 on 2022-11-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactus',
            new_name='Contactu',
        ),
    ]
