# Generated by Django 4.1.3 on 2022-11-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0003_customer_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='image',
            field=models.ImageField(blank=True, upload_to='Static\\Dataimage'),
        ),
    ]
