# Generated by Django 4.1.3 on 2022-12-06 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Office', '0007_alter_ourservice_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.CreateModel(
            name='Aboutmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Database Image/Aboutcompany')),
                ('Company', models.CharField(choices=[('B Group Of Group', 'B Group Of Group'), ('Travel and Tourism Group', 'Travel and Tourism Group'), ('Investment Group', 'Investment Group')], max_length=256)),
                ('Desc', models.CharField(max_length=500)),
                ('Icon', models.ImageField(upload_to='Database Image/Abouticon')),
                ('Designation', models.CharField(max_length=100)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
