# Generated by Django 4.1.3 on 2022-12-06 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Office', '0008_alter_customer_table_aboutmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboutmessage',
            new_name='About',
        ),
    ]
