# Generated by Django 4.1.3 on 2022-12-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0009_rename_aboutmessage_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Icon',
            field=models.ImageField(upload_to='Abouticon'),
        ),
        migrations.AlterField(
            model_name='about',
            name='Image',
            field=models.ImageField(upload_to='Aboutcompany'),
        ),
    ]
