# Generated by Django 4.1.3 on 2022-12-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0010_alter_about_icon_alter_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March ', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August')], max_length=256)),
            ],
        ),
    ]
