# Generated by Django 4.1.3 on 2022-12-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0014_rename_listd_iv_ourservice_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourserviceq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Dataimage')),
                ('title', models.CharField(max_length=100)),
                ('people', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('list_i', models.CharField(max_length=100)),
                ('list_ii', models.CharField(max_length=100)),
                ('list_iii', models.CharField(max_length=100)),
                ('list_iv', models.CharField(blank=True, max_length=100)),
                ('list_v', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ourservice',
        ),
    ]
