# Generated by Django 4.1.3 on 2022-12-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Office', '0015_ourserviceq_delete_ourservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ourserviceq',
            new_name='Ourservice',
        ),
    ]
